apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "todo-api-siva.fullname" . }}-test-connection"
  labels:
    {{- include "todo-api-siva.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ['curl', '{{ include "todo-api-siva.fullname" . }}:{{ .Values.service.port }}/api/todos']
  restartPolicy: Never
